### ISSUE TITLE
Provide a downloader for dynamodb

### ISSUE THREAD

**Issue by fizyk** [ClearcodeHQ/pytest-dynamodb#6]
pytest-dynamodb should provide the means to download the dynamoDB package automatically, if it's not present at the defined location.

**Comment by luqasz** [comment]
How (using which library etc) would you like to download dynamodb ?

**Comment by fizyk** [comment]
as simple as possible. shouldn't be too much hassle to use httplib

**Comment by luqasz** [comment]
Ok. IMO downloader is unnecessary since every one can do it on his/her own and it is done once. Decision is yours of course. `httplib` better than pulling `requests` package for such a simple task.
